name: lenat_mobile
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  chapasdk: ^0.0.8+1
  connectivity_plus: ^6.1.3
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.1.0
  get_it: ^8.0.3
  google_generative_ai: ^0.4.7
  # gpt_markdown: ^1.0.9
  graphql_flutter: ^5.2.0
  hugeicons: ^0.0.11
  image_picker: ^1.0.7
  minio: ^3.5.7
  loading_animation_widget: ^1.3.0
  pinput: ^5.0.1
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1
  cached_network_image: ^3.4.1
  flutter_blurhash: ^0.9.1
  flutter_html: ^3.0.0
  easy_image_viewer: ^1.5.1
  flutter_launcher_icons: ^0.14.4
  flutter_inappwebview: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/svg/

fonts:
  - family: NotoSansEthiopic
    fonts:
      - asset: assets/fonts/NotoSansEthiopic/NotoSansEthiopic-Light.ttf
        weight: 300
      - asset: assets/fonts/NotoSansEthiopic/NotoSansEthiopic-Regular.ttf
        weight: 400
      - asset: assets/fonts/NotoSansEthiopic/NotoSansEthiopic-Medium.ttf
        weight: 500
      - asset: assets/fonts/NotoSansEthiopic/NotoSansEthiopic-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/NotoSansEthiopic/NotoSansEthiopic-Bold.ttf
        weight: 700
